const books = [
    {
        id: 1,
        img: 'https://pngimg.com/uploads/book/book_PNG51090.png',
        title: 'Faith',
        author: 'David Adams',
        progress: '72%',
        lastOpened: '12 Minutes Ago',
        genre: 'Fiction',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A laboriosam neque nihil provident quia quibusdam quidem veritatis. Adipisci consequuntur corporis culpa enim est ex facilis in incidunt ipsam ipsum itaque labore maxime minus necessitatibus, nemo quaerat rerum saepe sunt? Accusantium alias consequuntur et excepturi minima obcaecati possimus reprehenderit unde, vel.\n',
    },
    {
        id: 2,
        img: 'https://toppng.com/uploads/preview/book-11549420966kupbnxvyyl.png',
        title: 'The world of ice',
        author: 'George R.',
        progress: '68%',
        lastOpened: '24 Minutes Ago',
        genre: 'Fantasy',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A laboriosam neque nihil provident quia quibusdam quidem veritatis. Adipisci consequuntur corporis culpa enim est ex facilis in incidunt ipsam ipsum itaque labore maxime minus necessitatibus, nemo quaerat rerum saepe sunt? Accusantium alias consequuntur et excepturi minima obcaecati possimus reprehenderit unde, vel.\n',
    },
    {
        id: 3,
        img: 'https://clipart.info/images/ccovers/150369121310-open-book-png-image.png',
        title: 'The power of Habit',
        author: 'Charles Duhigg',
        progress: '55%',
        lastOpened: '58 Minutes Ago',
        genre: 'Education',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A laboriosam neque nihil provident quia quibusdam quidem veritatis. Adipisci consequuntur corporis culpa enim est ex facilis in incidunt ipsam ipsum itaque labore maxime minus necessitatibus, nemo quaerat rerum saepe sunt? Accusantium alias consequuntur et excepturi minima obcaecati possimus reprehenderit unde, vel.\n',
    },
    {
        id: 4,
        img: 'https://flyclipart.com/thumb2/book-png-transparent-book-images-94930.png',
        title: 'Wild Wisdom',
        author: 'Neil Douglas',
        progress: '100%',
        lastOpened: '10 Minutes Ago',
        genre: 'Adventure',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A laboriosam neque nihil provident quia quibusdam quidem veritatis. Adipisci consequuntur corporis culpa enim est ex facilis in incidunt ipsam ipsum itaque labore maxime minus necessitatibus, nemo quaerat rerum saepe sunt? Accusantium alias consequuntur et excepturi minima obcaecati possimus reprehenderit unde, vel.\n',
    },
    {
        id: 5,
        img: 'https://www.pxpng.com/public/uploads/preview/-11602951895jjxzwwq18c.png',
        title: 'The sky at night',
        author: 'Chris North',
        progress: '45%',
        lastOpened: '35 Minutes Ago',
        genre: 'Science',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A laboriosam neque nihil provident quia quibusdam quidem veritatis. Adipisci consequuntur corporis culpa enim est ex facilis in incidunt ipsam ipsum itaque labore maxime minus necessitatibus, nemo quaerat rerum saepe sunt? Accusantium alias consequuntur et excepturi minima obcaecati possimus reprehenderit unde, vel.\n',
    },
    {
        id: 6,
        img: 'https://freepngimg.com/thumb/book/17-books-png-image.png',
        title: 'Into Thin Air',
        author: 'Jon Krakauer',
        progress: '15%',
        lastOpened: '5 Minutes Ago',
        genre: 'Nature',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A laboriosam neque nihil provident quia quibusdam quidem veritatis. Adipisci consequuntur corporis culpa enim est ex facilis in incidunt ipsam ipsum itaque labore maxime minus necessitatibus, nemo quaerat rerum saepe sunt? Accusantium alias consequuntur et excepturi minima obcaecati possimus reprehenderit unde, vel.\n',
    },
    {
        id: 7,
        img: 'http://www.downloadclipart.net/large/book-png-photos.png',
        title: 'Wonders on the world',
        author: 'Lonely planet',
        progress: '75%',
        lastOpened: '40 Minutes Ago',
        genre: 'Education',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A laboriosam neque nihil provident quia quibusdam quidem veritatis. Adipisci consequuntur corporis culpa enim est ex facilis in incidunt ipsam ipsum itaque labore maxime minus necessitatibus, nemo quaerat rerum saepe sunt? Accusantium alias consequuntur et excepturi minima obcaecati possimus reprehenderit unde, vel.\n',
    },
    {
        id: 8,
        img: 'https://www.pxpng.com/public/uploads/preview/-11602081952hxgrrf8mzn.png',
        title: 'Humans',
        author: 'Brandon Stanton',
        progress: '20%',
        lastOpened: '34 Minutes Ago',
        genre: 'Fantasy',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A laboriosam neque nihil provident quia quibusdam quidem veritatis. Adipisci consequuntur corporis culpa enim est ex facilis in incidunt ipsam ipsum itaque labore maxime minus necessitatibus, nemo quaerat rerum saepe sunt? Accusantium alias consequuntur et excepturi minima obcaecati possimus reprehenderit unde, vel.\n',
    },
    {
        id: 9,
        img: 'https://images.pngnice.com/download/2007/Book-PNG-File.png',
        title: 'Paint a new Scene',
        author: 'Deirdre O`Dare',
        progress: '50%',
        lastOpened: '8 Minutes Ago',
        genre: 'Romance',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A laboriosam neque nihil provident quia quibusdam quidem veritatis. Adipisci consequuntur corporis culpa enim est ex facilis in incidunt ipsam ipsum itaque labore maxime minus necessitatibus, nemo quaerat rerum saepe sunt? Accusantium alias consequuntur et excepturi minima obcaecati possimus reprehenderit unde, vel.\n',
    },
    {
        id: 10,
        img: 'https://w7.pngwing.com/pngs/875/325/png-transparent-book-cover-graphy-old-book-bookcase-used-book-textbook.png',
        title: 'Empower Yourself',
        author: 'Xenia Tchoumi',
        progress: '100%',
        lastOpened: '15 Minutes Ago',
        genre: 'Travel',
        description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. A laboriosam neque nihil provident quia quibusdam quidem veritatis. Adipisci consequuntur corporis culpa enim est ex facilis in incidunt ipsam ipsum itaque labore maxime minus necessitatibus, nemo quaerat rerum saepe sunt? Accusantium alias consequuntur et excepturi minima obcaecati possimus reprehenderit unde, vel.\n',
    },
]

export {books}